# Timeout for commands that take too long
command_timeout = 500

# Newline between prompts
add_newline = true

format = """
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$ruby\
$aws\
$docker_context\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"

[directory]
truncation_length = 3
truncate_to_repo = true
style = "bold cyan"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bold green"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"
conflicted = "="
ahead = "â‡¡${count}"
behind = "â‡¢${count}"
diverged = "â‡¡${ahead_count}â‡¢${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
deleted = "âœ˜${count}"

[nodejs]
format = "[$symbol($version)]($style) "
symbol = "â¬¢ "
detect_files = ["package.json", ".nvmrc"]
style = "green"

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = "ğŸ "
style = "yellow"

[ruby]
format = "[$symbol($version)]($style) "
symbol = "ğŸ’ "
style = "red"

[aws]
format = '[$symbol($profile)(\($region\))]($style) '
symbol = "â˜ï¸  "
style = "bold orange"

[docker_context]
format = "[$symbol$context]($style) "
symbol = "ğŸ³ "
style = "blue"
only_with_files = true

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
style = "bold yellow"
